bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-neoantigenpipeline_logo_light.png
    - docs/images/nf-core-neoantigenpipeline_logo_light.png
    - docs/images/nf-core-neoantigenpipeline_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-neoantigenpipeline_logo_light.png
    - docs/images/nf-core-neoantigenpipeline_logo_light.png
    - docs/images/nf-core-neoantigenpipeline_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config: false
  included_configs: false
nf_core_version: 3.0.2
org_path: msk
repository_type: pipeline
template:
  author: Nikhil Kumar
  description: Pipeline for computing neoantigen qualities from DNA and RNA-Seq data
  force: false
  is_nfcore: false
  name: neoantigenpipeline
  org: mskcc
  outdir: .
  skip_features: []
  version: 1.0.0
update: null
